### ISSUE TITLE
code 404, message File not found

### ISSUE THREAD

**Issue by historical-theology** [Kazark/timeline#1]
All seems to go properly with the following steps, per the Readme:

`git clone git clone https://github.com/Kazark/timeline`
`cd timeline`
`npm install`
`npm run serv3` (or any of the other options -- tested)

The terminal then reads:

`Serving HTTP on 0.0.0.0 port 5000 (http://0.0.0.0:5000/) ... `

However, when trying to open the timeline in a web browser (tried Firefox, Netsurf, Dillo, and elinks), the page is blank, and the terminal reads:

`"GET /elm.js HTTP/1.1" 404 -`
`code 404, message File not found`

I notice that elm.js is listed in this repository's Gitignore and (therefore) not included. Thoughts?

Thanks. God bless.

**Comment by Kazark** [comment]
I haven't touched this project in a while (and it is quite behind in terms of what I've learned: I have not been adding stuff) so I'll have to get it up and going again on my new laptop to see if I can replicate the issue. I remember so little about how this works that I can't suggest anything without looking at it further. I will try to take a look, though.

**Comment by Kazark** [comment]
@historical-theology okay, I think that error means you haven't built it. However, it looks like I still have this on Elm 0.18.0, and as I recall, v0.19.0 had significant breaking changes. I'm a bit unsure about how to get the 0.18.0 binaries that are probably needed for building this now. Let me test it. If I can get it working maybe I will just check in `elm.js`.

**Comment by Kazark** [comment]
Yeah, don't know how to install 0.18.0 anymore. Trying to see if I can run `elm-upgrade` and get on the latest. I should check in the `.js` since I don't actively maintain this and don't trust what the Elm people are going to do. (If I ever get the drive to revive this project, I probably do it in PureScript or ReScript.)

**Comment by Kazark** [comment]
Hm, `elm-format` worked, but I got an exception on `elm-upgrade`, and it did nothing. :thinking:

**Comment by Kazark** [comment]
Ah! Uninstalled the `elm-upgrade` AUR and installed with `npm` instead; now it is at least running.

**Comment by Kazark** [comment]
Hm, it definitely didn't leave me in a working state though. Not even sure what `elm-make` is or if it exists anymore. I pushed up my attempt on the [elm-0.19](https://github.com/Kazark/timeline/tree/elm-0.19) branch. I'm going to abandon that approach for the moment and see if I have an old `elm.js` laying around on another machine somewhere.

**Comment by Kazark** [comment]
Oh wow, I forgot how much I have in this. BTW my original idea was to have a lot more types of events and other data, and even provide a query language that would allow you to manipulate the view. Right now it's just lots of names, and if you don't know who they are, or if you are overwhelmed by the volume, oh well...

**Comment by Kazark** [comment]
Fixed by a2bcfd62d8fcceec373fdee8aa3a3f3074ae1c40.

**Comment by Kazark** [comment]
What remains unfixed: I don't know what you were intending to do with this (fairly cool, but) ramshackle collection of information. If you wanted to enhance it at all (the middle ages are sparse at this time), how will we do that on Elm 0.18? Unless my old laptop is still running that version of Elm...

**Comment by historical-theology** [comment]
Thank you, @Kazark . I just browsed the timeline locally as-is with no problems!

I do not know Elm, and I am not a programmer (yet?). I simply wanted to find a tidy, self-hosted resource to share with students and colleagues. (See my WIP [awesome-theology](https://github.com/historical-theology/awesome-theology) list for examples). 

Is it possible to edit the dataset(s) in a standard text editor (e.g. Micro) in order to contribute? If so, please tell me how, remembering that this is (completely) new territory for me.

- - - - -

Foolishly, I tried editing the elm.js file directly (adding Maximus the Confessor between Gregory the Great and John of Damacus) to no avail. The tabs and everything are impossible to correct. Clearly, a procedure is supposed to build that elm file automatically in the first place, which is what you asked about above...

**Comment by Kazark** [comment]
The data is stored [here](https://github.com/Kazark/timeline/tree/master/src/Data), and I think the format is somewhat self-documenting. However, the trouble is that you need Elm 0.18.0 in order to build the `elm.js`. And eww, yuck, I see what you mean about that JavaScript file. That is brutal.

At some point I would like to revitalize this project, but I may do it differently. I would like it to be more feature-rich, and my overall philosophy of church history has changed as well, which could possibly affect the way I approach it.

I think the best road forward for what you want, however, is to try to finish the upgrade that I attempted to start, to Elm 0.19. That would take some reading and research for me to look into; I have not worked on Elm in a long time, having abandoned it for PureScript in my other web-based projects. If we could get it working on Elm 0.19, then I think you would find it fairly easy to add data, provided you had an Elm environment; which isn't excessively hard, if you are trying to get the latest version.

I can't promise I'll find time to look into that, but if I do I'll post here and let you know. In the meantime, I don't know what platform you are on, but it may be possible to get an Elm 0.18 environment working, if you research it. In that case, you'd be in business. You'd just have to rebuild whenever you added data.

**Comment by historical-theology** [comment]
I agree that the format is somewhat self-documenting, so contributing (many) entries there would not be a problem for me, _if you are able to get the code to compile again_.

I do not have any idea how one would bring this project to Elm 19. This is the first time that I ever have seen Elm, and I am an end user, mostly in Debian and Manjaro, rather than a programmer. I use everything in that awesome-theology repository, and items from various repositories that I have starred and forked, for my regular work as a scholar. For now, my 'upstream' is normally detailed error reports and that sort of thing :smile: 

Anyway, I see that you have this under the "Unlicense." I also have a nascent idea to build a massive timeline of Church history in plain Markdown as a standard GitHub repository. The idea would be that everyone can contribute, with no coding skills required, as long as he/she documents a credible source for each entry (Britannica or better, let us say). Of course, I would link back to this repository as one inspiration and convenient source for that project.

Let me know if you might be interested in 'switching' to do that with me, especially if this Elm stuff seems to be a dead end. (NB: I am looking at Markdown because it can be converted to a 'real' timeline with tidbits of CSS or simply browsed by itself in any terminal--and it is extremely intuitive. Other simple ideas are most welcome!)

**Comment by Kazark** [comment]
Understood regarding Elm 19. I will be sure to let you know if I get it working on that.

Regarding the Unlicense, that's right, you are welcome to make whatever use of this you want, with or without citation of this project; the information that I have gathered here I have got from books and Wikipedia (my lack of citation is one of the defects of this project in its current state). This was a learning project for me, not a teaching tool for others, when I first conceived it, thus the lack of citation and the somewhat random choice of information.

I looked around when I started this for a simple way to convert stuff to a timeline, but I didn't find any that did what I wanted. If you have found something good, I would be curious to see it. However I don't know how a co-operation would work out; judging by your credentials, you and I have widely divergent definitions of "church" such that if such a project were to proceed in earnest, we'd want to see rather different sets of things on the timeline. For example, I trace my spiritual lineage back to the apostles through [the northern Italian Alps](https://www.amazon.com/History-Waldenses-J-Wylie/dp/1519095171)*, not through Rome. It's true that in this project I have included many names of people I would even consider heretics; still, I think a collaboration would be hard without some sort of agreement on the definition of what church history means and is.

*Caveat: the description on Amazon doesn't agree entirely with the contents of the book.

**Comment by historical-theology** [comment]
This is an example of what can be done with Markdown for timelines: https://chrisrosser.net/posts/2020/06/05/wwb5-creating-timelines-with-markdown/ (I have not tested it myself, as of yet.)

Major events in the history of Christianity are major events in the history of Christianity. I think a collaboration would be fine, but I respectfully yield that decision to you.

For now, I hope that you (or someone else who should find this) will be able to get the code compiling again. 

God bless.

**Comment by Kazark** [comment]
Will take a look at that, thanks. If you do get the markdown stuff going, feel free to drop a link here. I would be curious to see what you have.
